[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace STM32F429ZITx with your chip as listed in `probe-rs chip list`
runner = "probe-rs run --chip=STM32F411CCUx --probe 1366:1020:000053000782"
# runner = "probe-rs run --chip=STM32F411CCUx --probe 0483:3748:28391306C29318303030303032"
[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
